// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void increase_temp(lv_event_t *e);
void set_preset_one(lv_event_t *e);
void decrease_temp(lv_event_t *e);
void set_preset_two(lv_event_t *e);
void toggle_pwr(lv_event_t *e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
