// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_Container2;
extern lv_obj_t *ui_Container3;
extern lv_obj_t *ui_Arc2;
extern lv_obj_t *ui_Container6;
extern lv_obj_t *ui_Label6;
extern lv_obj_t *ui_Label7;
extern lv_obj_t *ui_Container7;
extern lv_obj_t *ui_Label8;
extern lv_obj_t *ui_Container8;
extern lv_obj_t *ui_Label1;
extern lv_obj_t *ui_Label10;
extern lv_obj_t *ui_Label11;
extern lv_obj_t *ui_Container1;
extern lv_obj_t *ui_Container10;
extern void ui_event_Button2( lv_event_t * e);
extern lv_obj_t *ui_Button2;
extern lv_obj_t *ui_Label4;
extern void ui_event_Button3( lv_event_t * e);
extern lv_obj_t *ui_Button3;
extern lv_obj_t *ui_Label3;
extern lv_obj_t *ui_Label13;
extern lv_obj_t *ui_Container11;
extern void ui_event_Button1( lv_event_t * e);
extern lv_obj_t *ui_Button1;
extern lv_obj_t *ui_Label5;
extern void ui_event_Button5( lv_event_t * e);
extern lv_obj_t *ui_Button5;
extern lv_obj_t *ui_Label14;
extern lv_obj_t *ui_Label15;
extern lv_obj_t *ui_Container4;
extern lv_obj_t *ui_Container5;
extern lv_obj_t *ui_Label2;
extern void ui_event_Switch1( lv_event_t * e);
extern lv_obj_t *ui_Switch1;
extern lv_obj_t *ui_Container9;
extern lv_obj_t *ui_Image1;
extern lv_obj_t *ui_Label9;
// CUSTOM VARIABLES
extern lv_obj_t *uic_Screen1;
extern lv_obj_t *uic_Gauge;
extern lv_obj_t *uic_Temp;
extern lv_obj_t *uic_Target;
extern lv_obj_t *uic_Increase;
extern lv_obj_t *uic_Decrease;
extern lv_obj_t *uic_Pwr;
extern lv_obj_t *uic_Icon;
extern lv_obj_t *uic_Status;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

