// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t *ui_Splash = NULL;lv_obj_t *ui_Image2 = NULL;
// event funtions

// build funtions

void ui_Splash_screen_init(void)
{
ui_Splash = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Splash, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_flex_flow(ui_Splash,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Splash, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_set_style_bg_color(ui_Splash, lv_color_hex(0xFF5041), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Splash, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image2 = lv_img_create(ui_Splash);
lv_img_set_src(ui_Image2, &ui_img_1113032066);
lv_obj_set_width( ui_Image2, 221);
lv_obj_set_height( ui_Image2, 50);
lv_obj_set_align( ui_Image2, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Image2,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Image2, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_add_flag( ui_Image2, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_Image2,255);
ui_object_set_themeable_style_property(ui_Image2, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR, _ui_theme_color_white);
ui_object_set_themeable_style_property(ui_Image2, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR_OPA, _ui_theme_alpha_white);

}

void ui_Splash_screen_destroy(void)
{
   if (ui_Splash) lv_obj_del(ui_Splash);

// NULL screen variables
ui_Splash= NULL;
ui_Image2= NULL;

}
