// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _UI_THEMES_H
#define _UI_THEMES_H

#ifdef __cplusplus
extern "C" {
#endif

#define UI_THEME_COLOR_PRIMARY 0
#define UI_THEME_COLOR_SECONDARY 1
#define UI_THEME_COLOR_WHITE 2
#define UI_THEME_COLOR_DANGER 3
#define UI_THEME_COLOR_INFO 4

#define UI_THEME_DEFAULT 0

#define UI_THEME_YELLOW 1

extern const ui_theme_variable_t _ui_theme_color_primary[2];
extern const ui_theme_variable_t _ui_theme_alpha_primary[2];

extern const ui_theme_variable_t _ui_theme_color_secondary[2];
extern const ui_theme_variable_t _ui_theme_alpha_secondary[2];

extern const ui_theme_variable_t _ui_theme_color_white[2];
extern const ui_theme_variable_t _ui_theme_alpha_white[2];

extern const ui_theme_variable_t _ui_theme_color_danger[2];
extern const ui_theme_variable_t _ui_theme_alpha_danger[2];

extern const ui_theme_variable_t _ui_theme_color_info[2];
extern const ui_theme_variable_t _ui_theme_alpha_info[2];

extern const uint32_t* ui_theme_colors[2];
extern const uint8_t* ui_theme_alphas[2];
extern uint8_t ui_theme_idx;

void ui_theme_set(uint8_t theme_idx);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
