// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

const ui_theme_variable_t _ui_theme_color_primary[2] = {0xF9A92E, 0xF9A92E};
const ui_theme_variable_t _ui_theme_alpha_primary[2] = {255, 255};

const ui_theme_variable_t _ui_theme_color_secondary[2] = {0x1B202C, 0x1B202C};
const ui_theme_variable_t _ui_theme_alpha_secondary[2] = {255, 255};

const ui_theme_variable_t _ui_theme_color_white[2] = {0xFFFFFF, 0xFFFFFF};
const ui_theme_variable_t _ui_theme_alpha_white[2] = {255, 255};

const ui_theme_variable_t _ui_theme_color_danger[2] = {0xF44336, 0xF44336};
const ui_theme_variable_t _ui_theme_alpha_danger[2] = {255, 255};

const ui_theme_variable_t _ui_theme_color_info[2] = {0x2962FF, 0x2962FF};
const ui_theme_variable_t _ui_theme_alpha_info[2] = {255, 255};
uint8_t ui_theme_idx = UI_THEME_YELLOW;

void ui_theme_set(uint8_t theme_idx)
{
    ui_theme_idx = theme_idx;
    _ui_theme_set_variable_styles(UI_VARIABLE_STYLES_MODE_FOLLOW);
}

