list(
  APPEND
  LV_EDITOR_PROJECT_SOURCES
  ${CMAKE_CURRENT_LIST_DIR}/components/navigation/header/header_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/navigation/navigation_bar/navigation_bar_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/navigation/navigation_button/navigation_button_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/font_lg_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/font_md_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/font_sm_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/font_xs_data.c
  ${CMAKE_CURRENT_LIST_DIR}/lvgl_ui_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/lvgl_ui.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/home/home_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/info/info_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/manual/manual_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/profiles/profiles_gen.c)